# Generated by Django 4.2.30 on 2026-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
