# Generated by Django 4.2.30 on 2026-07-26 06:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_galleryimage_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-year', '-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-year', '-published_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='year',
            field=models.PositiveIntegerField(default=core.models.current_year),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='year',
            field=models.PositiveIntegerField(default=core.models.current_year),
        ),
    ]
