# Generated by Django 4.2.30 on 2026-07-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cause',
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
    ]
